"""change Cafe.phone field

Revision ID: 121fe2192262
Revises: fa0e7d6e4855
Create Date: 2026-06-12 11:19:16.840092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121fe2192262'
down_revision: Union[str, Sequence[str], None] = 'fa0e7d6e4855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cafes', 'phone',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'cafes', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cafes', type_='unique')
    op.alter_column('cafes', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
