"""remove CafeManager model, create Cafe-User relationship

Revision ID: 71cc279c2f5a
Revises: a765bb31fe72
Create Date: 2026-06-11 20:17:01.617135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71cc279c2f5a'
down_revision: Union[str, Sequence[str], None] = 'a765bb31fe72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe_managers')
    op.add_column('users', sa.Column('cafe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'cafes', ['cafe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'cafe_id')
    op.create_table('cafe_managers',
    sa.Column('cafe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], name=op.f('cafe_managers_cafe_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cafe_managers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cafe_id', 'user_id', 'id', name=op.f('cafe_managers_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('cafe_managers_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
