"""create TimeSlot model

Revision ID: 2e84449e8cd5
Revises: a929ffae6d1b
Create Date: 2026-06-09 16:28:01.819095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e84449e8cd5'
down_revision: Union[str, Sequence[str], None] = 'a929ffae6d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslots',
    sa.Column('cafe_id', sa.Integer(), nullable=False, comment='ID кафе'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Время начала слота'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Время окончания слота'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание слота'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_time_order'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeslots')
    # ### end Alembic commands ###
