"""add guest_number field to Booking

Revision ID: 34ecaac8eb3e
Revises: b8ec1d114629
Create Date: 2026-06-15 04:35:01.995764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ecaac8eb3e'
down_revision: Union[str, Sequence[str], None] = 'b8ec1d114629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guest_number', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'guest_number')
    # ### end Alembic commands ###
